import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import axios from 'axios';


export default function Home(props) {
  return (
    <>
    {props.value}
    <br/>
    {props.name}
    </>
    // <div className={styles.container}>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    
    //     <h1 className={styles.title}>
    //     <Link href="/home"><a>Home</a></Link>
    //     </h1>

            
    // </div>
  )
}


export const getServerSideProps=async()=>{

  const isAuthenticated=false;
  if(!isAuthenticated)
  {
     return {
            redirect:{destination:'/home',permanent:false }
    }
  }
 //const value='welcome to the open weaver';
 //const name='rajasekar';
 //console.log("name===>",name);
  return{
    props:{value}
  }



}

function getKandiMessage(){

  let url='https://api.kandi.dev/consumer/home/gethomepagemessages/landingPage';
   return axios.get(url).then(res=>{
     return (res.data)?res.data:{}
   }).catch(err=>{
     return {};
   })

}

//https://api.kandi.dev/consumer/home/gethomepagemessages/landingPage